import os
import logging
from typing import Dict, Any, List
from ..graph.knowledge_graph import KnowledgeGraphManager
from ..utils.trace_logger import default_trace

logger = logging.getLogger(__name__)

class ArchivistAgent:
    def __init__(self, repo_path: str, kg_manager: KnowledgeGraphManager):
        self.repo_path = repo_path
        self.kg_manager = kg_manager

    def generate_CODEBASE_md(self) -> str:
        """
        Synthesizes the living context file structured for AI coding agents.
        """
        logger.info("Generating CODEBASE.md...")
        
        # 1. Architecture Overview
        # (Using a summary of the most connected modules)
        pagerank = self.kg_manager.compute_pagerank()
        top_hubs = sorted(pagerank.items(), key=lambda x: x[1], reverse=True)[:5]
        
        # 2. Critical Path (Top 5 PageRank)
        critical_path = "\n".join([f"- `{h[0]}` (Importance: {h[1]:.4f})" for h in top_hubs])
        
        # 3. Data Sources & Sinks (from Hydrologist)
        sources = set()
        targets = set()
        for u, v, data in self.kg_manager.lineage_graph.edges(data=True):
            sources.add(u)
            targets.add(v)
        
        # Filters: sources that are never targets, targets that are never sources
        entry_points = sources - targets
        exit_points = targets - sources
        
        # 4. Known Debt (Circular deps + Doc Drift)
        drift_modules = [m.path for m in self.kg_manager.data_store.modules if m.is_doc_drift]
        
        # 5. High-Velocity Files (Git frequency)
        velocity_files = sorted(self.kg_manager.data_store.modules, key=lambda m: m.change_frequency, reverse=True)[:5]
        velocity_list = "\n".join([f"- `{m.path}` ({m.change_frequency} commits in 30d)" for m in velocity_files])

        # 6. Module Purpose Index
        purpose_index = "\n".join([f"### `{m.path}`\n- **Purpose**: {m.purpose_statement}\n- **Domain**: {m.domain_cluster}" for m in self.kg_manager.data_store.modules[:50]])

        md_content = f"""# CODEBASE.md - Living Context

> [!NOTE]
> This file is generated by the Brownfield Cartographer. It contains a synthesized architectural context for AI agents.

## 🏗️ Architecture Overview
The system is composed of {len(self.kg_manager.data_store.modules)} modules across {len(set(m.domain_cluster for m in self.kg_manager.data_store.modules))} business domains. The architecture is primarily driven by data transformations and utility-heavy hubs.

## 🚀 Critical Path (Top Hubs)
{critical_path}

## 🌊 Data Flow
### Entry Points (Sources)
{", ".join([f"`{s}`" for s in list(entry_points)[:10]]) if entry_points else "No pure sources detected."}

### Exit Points (Sinks)
{", ".join([f"`{t}`" for t in list(exit_points)[:10]]) if exit_points else "No pure sinks detected."}

## ⚠️ Known Debt & Risks
### Documentation Drift (Implementation != Documentation)
{", ".join([f"`{d}`" for d in drift_modules[:10]]) if drift_modules else "No significant drift detected."}

### Potential Circular Dependencies
(Analyzed in lineage_graph.json)

## 📈 Recent Change Velocity (Hotspots)
{velocity_list}

## 📖 Module Purpose Index
{purpose_index}
"""
        # Log action to trace
        default_trace.log_action(
            agent="Archivist",
            action="generate_CODEBASE_md",
            evidence="Synthesis of Knowledge Graph manager state",
            confidence=0.95,
            metadata={"modules": len(self.kg_manager.data_store.modules)}
        )
        
        return md_content
